# Generated by Django 4.2.24 on 2025-12-31 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_audioupload"),
    ]

    operations = [
        migrations.DeleteModel(name="audioupload",),
        migrations.AddField(
            model_name="post",
            name="banner",
            field=models.ImageField(blank=True, default="fallback.png", upload_to=""),
        ),
    ]
